ヘッダー部分の画面開発
I-BIS-dev/hammers_corporate-site pull request #22
Opened 2023-10-05 04:39 UTC by kurokirishima-jiejie

## why
#1 

## what
- レイアウト作成
- レスポンシブ対応

https://github.com/I-BIS-dev/hammers_corporate-site/assets/133887892/df000d39-9064-49d4-a651-17c4336974ab

2023-10-08 15:08 UTC, kurokirishima-jiejie commented on assets/js/main.js
> +  const ham = $('#js-hamburger');
`#js-humburger`と`#js-nav`をグローバルナビとハンバーガーボタンに付与し
hamとnavに格納
ハンバーガーボタン押下時にjs-active（ハンバーガーアニメーションのクラス）と
js-open（sp時のグローバルナビ）が表示される

2023-10-08 15:09 UTC, kurokirishima-jiejie commented on assets/scss/foundation/_base.scss
> +  max-width: 1280px;
body内でコンテンツの要素を制御するための`max-width`を設定

2023-10-08 15:11 UTC, kurokirishima-jiejie commented on assets/scss/layout/_header.scss
> +        opacity: 0;
1024px以下になるとグローバルナビが非表示になる

2023-10-08 15:14 UTC, kurokirishima-jiejie commented on assets/scss/object/component/_contact.scss
> +.c-contact {
sp時の問い合わせボタン

2023-10-08 15:15 UTC, kurokirishima-jiejie commented
@MogmogTaro 
お疲れ様です！
header部分の開発ですが、
ボタン押下時の動きまで実装できました。

レビューよろしくお願いいたします🤲

2023-10-09 06:58 UTC, MogmogTaro requested changes
全体的によく書けていると思います。
一部ルールに沿っていない部分がありましたのでそちらコメントしました

2023-10-09 06:58 UTC, MogmogTaro commented on assets/js/main.js
> +    ham.toggleClass('js-active');
ここはjs-activeではなく、--activeのようなmodifireを作ってそちらでstyleを変更するようにしてください

2023-10-09 06:58 UTC, MogmogTaro commented on assets/scss/foundation/_base.scss
> +// * {
コメントアウトは不要であれば消しましょう

2023-10-09 06:58 UTC, MogmogTaro commented on assets/scss/layout/_header.scss
> +.js-open {
jsのクラス,idにstyleはつけない
styleが必要であれば、--open等のmodifireで変更してください

2023-10-09 06:58 UTC, MogmogTaro commented on assets/scss/layout/_header.scss
> +.js-active .l-header__hamburger--border:nth-child(1) {
--activeになればまた場所も変わると思いますが、
sassなので空のクラスもきちんと構造化しましょう

2023-10-09 10:34 UTC, kurokirishima-jiejie commented
@MogmogTaro 
レビューの修正が完了しました。
ご確認よろしくお願いいたします。

2023-10-09 15:08 UTC, kurokirishima-jiejie commented on assets/scss/object/component/_button.scss
> +// ハンバーガーメニュー
ハンバーガーメニューはコンポーネント化しました

2023-10-10 05:01 UTC, MogmogTaro requested changes
コメントしました。
コメントした箇所のルールが掴めてくれば良いかなと思います

2023-10-10 05:01 UTC, MogmogTaro commented on assets/js/main.js
> +    ham.toggleClass('--active');
cssのコメントでも書きましたが、jsにmodifireをつけるのではなく
クラスにつけるよう定義しましょう
（--openも同様）

2023-10-10 05:13 UTC, kurokirishima-jiejie commented on assets/js/main.js
> +    ham.toggleClass('--active');
クラスにつけるという意味が理解できません
`  const ham = $('.l-header__hamburger');`などに変更すれば良いのでしょうか？

2023-10-10 05:16 UTC, kurokirishima-jiejie commented on assets/scss/object/component/_button.scss
> +.--active .l-header__hamburger--border:nth-child(1) {
ここの構造化の部分が理解できないので正解を教えていただけませんか？

2023-10-10 05:17 UTC, MogmogTaro commented on assets/js/main.js
> +    ham.toggleClass('--active');
@kurokirishima-jiejie 
あー、よくよくみるとここは変更しなくても良いのですが
cssが `.--open` `.--active`と単独になっているので、そうではなくて
```
.l-header-hoge {
  &.--active {}
}
```
にしましょうね、という内容です。

なので、`const ham = $('.l-header__hamburger');`にした方が見返した時にわかりやすいとは思います

2023-10-10 05:18 UTC, MogmogTaro commented on assets/scss/object/component/_button.scss
> +.--active .l-header__hamburger--border:nth-child(1) {
```
.--active {
   .l-header__hamburger--border {
    &:nth-child(1) { hoge }
    &:nth-child(2) { hoge }
    &:nth-child(3) { hoge }
  }
}
```

2023-10-10 05:20 UTC, MogmogTaro commented on assets/scss/object/component/_button.scss
> +.--active .l-header__hamburger--border:nth-child(1) {
ただし.--activeは`l-header__hamburger`につくmodifireなので、
厳密には
```
.l-header__hamburger {
  .--active {
     .l-header__hamburger--border {
      &:nth-child(1) { hoge }
      &:nth-child(2) { hoge }
      &:nth-child(3) { hoge }
    }
  }
}```

2023-10-10 05:35 UTC, kurokirishima-jiejie commented
@MogmogTaro 
修正しました！
jsの部分は`js-hoge`とidがついていた方が管理しやすいのでそのままにしています！
ご確認よろしくお願いいたします

2023-10-10 08:12 UTC, MogmogTaro approved these changes
OKです🙆‍♀️
一旦マージして、fotterの方のコンフリクトの様子を見ましょう

2023-10-10 08:13 UTC, merged