【WIP】会社概要ページの画面開発
I-BIS-dev/hammers_corporate-site pull request #28
Opened 2023-10-12 08:35 UTC by kurokirishima-jiejie

## why
#7 

## what

<img width="1774" alt="image" src="https://github.com/I-BIS-dev/hammers_corporate-site/assets/133887892/04418823-e79c-448f-a9ec-b0c45d3c9c51">

2023-10-16 02:11 UTC, kurokirishima-jiejie commented
@MogmogTaro 
会社概要ページの画面開発が完成しました。
ご確認よろしくお願いいたします。

2023-10-16 14:50 UTC, MogmogTaro commented
@kurokirishima-jiejie 
 ヘッダースクロール時は透過させないでください
 それと、画面収録ではなくPC/SPの全体のスクショをWhatにはってください

2023-10-16 14:54 UTC, MogmogTaro requested changes
レビューしました
もう１つコメントにも書きましたが、画面収録ではなくスクショを貼ってください（わかりにくいので）

2023-10-16 14:54 UTC, MogmogTaro commented on assets/scss/layout/_company.scss
> +main {
これはなぜ個別のセレクタ指定してるのですか？

2023-10-16 14:54 UTC, MogmogTaro commented on assets/scss/layout/_company.scss
> +        iframe {
googleもクラスつけてください

2023-10-16 14:54 UTC, MogmogTaro commented on company/index.html
> +        <div class="l-adress2">
2というのが何を意味しているのかわからないの命名変更してください

2023-10-16 14:54 UTC, MogmogTaro commented on company/index.html
> +      <div class="p-inner">
ここで急にp-innerが出てきたのは・・・？

2023-10-17 05:01 UTC, kurokirishima-jiejie commented on company/index.html
> +      <div class="p-inner">
topページ同様、コンテンツ幅を1000pxで制御し中央に整列させるためです。
この部分はtopページから流用した共通部分なので他の下層ページも同じ設定にしております。

```
.p-inner {
  max-width: 1000px;
  margin: 0 auto;

  @include mq(sp-ls) {
    padding: 0 8px;
  }
}
```

2023-10-17 05:15 UTC, kurokirishima-jiejie commented on assets/scss/layout/_company.scss
> +main {
忘れていました。
`main`>`.main`とクラス名を付与しました

2023-10-17 05:18 UTC, kurokirishima-jiejie commented
@MogmogTaro 
お疲れ様です！
レビューの修正を行いました！

なお、その他PRでも完成版（PC/SP）のスクショを添付しました。

2023-10-17 13:06 UTC, MogmogTaro commented
@kurokirishima-jiejie 
PCのスクショ違くないですか？

2023-10-17 13:08 UTC, MogmogTaro requested changes
コメントしました

2023-10-17 13:08 UTC, MogmogTaro commented on company/index.html
> +      <h1 class="l-header__logo-name"><a class="u-header__logo" href="#">BESTER</a></h1>
下層ページのh1はタイトルと同じものにしてください

2023-10-17 13:08 UTC, MogmogTaro commented on company/index.html
> +  <title>株式会社ハマーズ</title>
下層ページのタイトルにする

2023-10-17 13:09 UTC, MogmogTaro commented
SPのスクショが違うのか

2023-10-18 00:38 UTC, kurokirishima-jiejie commented on company/index.html
> +  <title>株式会社ハマーズ</title>
@MogmogTaro 
`<title>株式会社ハマーズ/会社概要</title>`こういうイメージですか？
それとも会社概要のみでいいですか？

2023-10-18 01:08 UTC, kurokirishima-jiejie commented
@MogmogTaro 

修正完了したためマージします！

2023-10-18 01:08 UTC, merged