【WIP】ベスターの強みページの画面開発
I-BIS-dev/hammers_corporate-site pull request #30
Opened 2023-10-16 02:52 UTC by kurokirishima-jiejie

## why
#4 

## what

2023-10-16 08:29 UTC, kurokirishima-jiejie commented
@MogmogTaro 
ベスターの強みページが完成しました。
お手隙の際、レビューよろしくお願いいたします。

2023-10-16 14:55 UTC, MogmogTaro requested changes
細かいデザインに関しては全体のスクショ見てコメントします

2023-10-17 11:12 UTC, kurokirishima-jiejie commented
@MogmogTaro 
お疲れ様です！
お手隙の際、レビューお願いいたします🤲

2023-10-17 13:11 UTC, MogmogTaro approved these changes
とりあえずApproveしておくので直したらマージしてください

2023-10-17 13:11 UTC, MogmogTaro commented on assets/scss/layout/_merit.scss
> +main {
このmainなんですか？
（どっかでもコメントした気がしますが

2023-10-17 13:11 UTC, MogmogTaro commented on assets/scss/object/utility/_color.scss
> +.--bg-color {
コンポーネントとして使うならu-
modifireなら変更したい箇所につける

2023-10-17 13:11 UTC, MogmogTaro commented on merit/index.html
> +  <title>株式会社ハマーズ</title>
ここも変更

2023-10-17 13:11 UTC, MogmogTaro commented on merit/index.html
> +      <h1 class="l-header__logo-name"><a class="u-header__logo" href="#">BESTER</a></h1>
ここも他PRのコメントと同様

2023-10-18 01:44 UTC, merged